//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CI2.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CI2Entities : DbContext
    {
        public CI2Entities()
            : base("name=CI2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<TabRol> TabRol { get; set; }
        public virtual DbSet<TabTareaUsuario> TabTareaUsuario { get; set; }
        public virtual DbSet<TabUsuario> TabUsuario { get; set; }
        public virtual DbSet<TabUsuarioLogin> TabUsuarioLogin { get; set; }
        public virtual DbSet<TabUsuarioReclamo> TabUsuarioReclamo { get; set; }
        public virtual DbSet<TabUsuarioRol> TabUsuarioRol { get; set; }
    }
}
