//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CI2.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabTareaUsuario
    {
        public long IdTarea { get; set; }
        public System.DateTime FechaVencimieno { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public string IdUsuario { get; set; }
    
        public virtual TabUsuario TabUsuario { get; set; }
    }
}
