//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CI2.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TabUsuario()
        {
            this.TabTareaUsuario = new HashSet<TabTareaUsuario>();
            this.TabUsuarioLogin = new HashSet<TabUsuarioLogin>();
            this.TabUsuarioReclamo = new HashSet<TabUsuarioReclamo>();
            this.TabUsuarioRol = new HashSet<TabUsuarioRol>();
        }
    
        public string IdUsuario { get; set; }
        public string Correo { get; set; }
        public bool CorreoConfirmacion { get; set; }
        public string Contrasena { get; set; }
        public string Seguridad { get; set; }
        public string Telefono { get; set; }
        public bool TelefonoConfirmacion { get; set; }
        public bool DosFactoresActivacion { get; set; }
        public Nullable<System.DateTime> FechaUltimoBloqueo { get; set; }
        public bool Bloqueo { get; set; }
        public int NumeroIngresosFallidos { get; set; }
        public string NombreUsuario { get; set; }
        public string Discriminator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabTareaUsuario> TabTareaUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabUsuarioLogin> TabUsuarioLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabUsuarioReclamo> TabUsuarioReclamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TabUsuarioRol> TabUsuarioRol { get; set; }
    }
}
