//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CI2.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabUsuarioReclamo
    {
        public int IdUsuarioReclamo { get; set; }
        public string IdUsuario { get; set; }
        public string TipoReclamo { get; set; }
        public string Reclamo { get; set; }
        public string IdentityUser_Id { get; set; }
    
        public virtual TabUsuario TabUsuario { get; set; }
    }
}
